# Generated by Django 2.0.2 on 2019-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(default=0, max_length=5)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('genre', models.CharField(blank=True, max_length=150, null=True)),
                ('imdb_score', models.IntegerField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
