# Generated by Django 2.0.2 on 2019-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190407_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
